name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Configuration
        run: |
          CONFIG_ENV=$(cat config.env | grep -w "CONFIG_ENV" | head -n 1 | cut -d "=" -f 2)
          echo "MODULE_PACKAGING_PATH=$(cat $CONFIG_ENV | grep -w "MODULE_PACKAGING_PATHE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "ZIP_FILENAME=$(cat $CONFIG_ENV | grep -w "ZIP_FILENAME" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "CONFIG_NAME=$(cat $CONFIG_ENV | grep -w "CONFIG_NAME" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "IS_PRERELEASE=$(cat $CONFIG_ENV | grep -w "IS_PRERELEASE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "VERSION=$(cat $CONFIG_ENV | grep -w "VERSION" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "FILE=$(cat $CONFIG_ENV | grep -w "FILE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "VERSIONCODE=$(cat $CONFIG_ENV | grep -w "VERSIONCODE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
      - name: Update VERSION
        run: |
          VERSIONCODE="${{ env.VERSIONCODE }}"
          VERSION="${{ env.VERSION }}"
          
          # 创建 intelligent.json 文件
          echo '{
            "versionCode": '"${VERSIONCODE}"',
            "version": "'"${VERSION}"'",
            "zipUrl": "https://github.moeyy.xyz/https://github.com/YumeYuka/intelligent/releases/download/'"${VERSION}"'/intelligent.zip",
            "changelog": "https://github.moeyy.xyz/https://github.com/YumeYuka/intelligent/blob/main/changelog.md"
          }' > intelligent.json
          
          
          # 创建 module.prop 文件
          echo 'id=id=Intelligent
          name=Intelligent
          version='"${VERSION}"'
          versionCode='"${VERSIONCODE}"'
          author=YumeYuka@Github.com
          description=智能分类文件，支持自定义配置.
          updateJson=https://github.moeyy.xyz/https://github.com/YumeYuka/intelligent/blob/main/intelligent.json
          ' > ./magisk/module.prop
      
      - name: Zip Module
        run: |
          sh $GITHUB_WORKSPACE/build.sh magisk intelligent.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 访问权限
        with:
          tag_name: ${{ env.VERSION }}
          body_path: ${{ github.workspace }}/changelog.md
          name: Tritium_${{ env.VERSION }}
          prerelease: ${{ env.IS_PRERELEASE }}
          body: ${{ env.RELEASE_NOTES }}

          files: |
              ./*.zip
          repository: YumeYuka/intelligent
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: 同步 repo
        run: |
          rm -rf ./*.zip
           rm -rf ./*.hash
          bash -c 'if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "工作树无变更，跳过提交步骤..."
          else
            echo "提交文件中..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore(generated): GitHub Actions Bot 提交的记录"
            git log -3 --oneline
            echo "推送更新中..."
            git push
          fi'